version: '2'
services:

  qgis:
    image: qgis/qgis:release-3_4
    environment:
      DISPLAY: ':99'
      WITH_PYTHON_PEP: 'true'
      MUTE_LOGS: 'true'
      ON_TRAVIS: 'true'
    volumes:
      - ./:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/inasafe
      - ./:/tests_directory
    entrypoint: /tests_directory/scripts/container_setup.sh
    command: qgis_testrunner.sh test_suite.test_package
    tty: true
    stdin_open: true
    working_dir: /tests_directory